name: Python CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
        tox-action:
          - lint
          - pytest
          - integration
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
          TOXENV=$(echo $TOXENV | sed 's/\.//') tox
        env:
          TOXENV: py${{ matrix.python-version }}-${{ matrix.tox-action }}
